попытка создать пулреквест с версткой первой страницы Седоны
htmlacademy-htmlcss/2426581-sedona-1 pull request #3
Opened 2023-11-07 20:11 UTC by Roman3723

2023-11-08 10:09 UTC, summertime-fms requested changes

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +  </ul>
лого отдельно
список отдельно
все это должно быть завернуто в `nav` (сейчас правильно)

лого представлено тегом `img` завернутым в тег `a`

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +  </ul>
спан с классом `visuaaly-hidden `в логотипе нам в данном случае не требуется потому что у `img` будет атрибут `alt` который и отвечает за доступность

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +        <!--не понимаю значение символа в макете - "корзина"? "понравилось"? "избранное"?-->
скорее всего избранное

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +      </a>
не совсем
это либо кнопка либо ссылка

то есть если мы по клику должны покидать текущую страницу и переходить на другую (по ТЗ или опираясь на логику) - это ссылка (тег `a`)

если по клику мы не покидаем текущую страницу а меняется что то в рамках текущей страницы - это кнопка (тег `button`)

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +      </a>
конкретно здесь у нас нет тз и мы можем выбрать то что считаем сами правильным

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +<!--сомневаюсь в именовани заголовка и atl-текста, поскольку выше уже есть ситуация с треугольником-логотипом, которая мне не ясна-->
Все вполне нормально)

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +</main>
ненужные отступы

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +  <section class="newsletter"><h2>Подпишитесь на рассылку</h2>
каждый тег с новой строки

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +      <button class="button newsletter-button" type="submit"><span class="visually-hidden">Подписаться</span>
спан не нужен

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +    <a class="button" href="#">
этот класс ты использовал в форме подписки на рассыоку. там кнопка выглядит как кнопка а тут соц сети не выглядят как кнопки. стилизовать будем по другому классу который и надо придумать

2023-11-08 10:09 UTC, summertime-fms commented on index.html
> +  <section class="footer-contacts">
на секцию не тянет)
секция это что то побольше

2023-11-09 09:48 UTC, Roman3723 commented on index.html
> +    <a class="button" href="#">
> этот класс ты использовал в форме подписки на рассыоку. там кнопка выглядит как кнопка а тут соц сети не выглядят как кнопки. стилизовать будем по другому классу который и надо придумать

Если речь об <a class="button"...> - я заимствовал верстку в примере "Барбершоп", где соцсети представлены таким же образом - как иконки, а не кнопки, но при этом с классом "button"

![присвоение класса соц сети  footer](https://github.com/htmlacademy-htmlcss/2426581-sedona-1/assets/148534470/f81ce74a-5cfc-47a1-bc49-812f69094abd)

2023-11-13 16:46 UTC, summertime-fms commented on index.html
> +    <a class="navigation-link" href="#">
hotels.html

2023-11-13 16:46 UTC, summertime-fms commented on index.html
> +  </p>
<a href="https://up.htmlacademy.ru/htmlcss-individual/1"></a>

2023-11-13 16:46 UTC, summertime-fms commented on index.html
удалить

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +</ul>
Список не очень хорошо тут использовать. 
Можно сгруппировать через div

У второй type="reset"

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +  <li><button class="button" type="submit">Сбросить</button>
c новой строки новый тег

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +  <form class="catalog-filter" action="https:/echo.html.ru/" method="get">
method = post

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +<section class="catalog-filter-group">
fieldset

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +<section class="catalog-filter-group">
fieldset

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +</ul>
добавить закрывающий тег form

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +</a>
это будут кнопки 

Не забывай кнопкам указывать `type="button"`

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +    <a class="hotel-card-button button" href="#">в избранное</a>
имеет смысл поменять на кнопку

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +  <!--Рейтинг: 6,9-->
Добавить рейтинг + img со звездочками

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +  </li>
закрывающий ul

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +        <input class="field" placeholder="Ваш e-mail"  type="email" name="newsletter-email" id="newsletter-email" required>
лейбл потерял

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +      <a class="button" href="https://youtube.com/user/htmlacademyru">
social-link

2023-11-13 16:46 UTC, summertime-fms commented on hotels.html
> +      <a class="footer-logo" href="https://htmlacademy.ru/">
copyright

2023-11-15 08:40 UTC, summertime-fms requested changes

2023-11-15 08:40 UTC, summertime-fms commented on hotels.html
> +      <img class="logo" src="#" alt="логотип Sedona">
Существует несколько атрибутов для оптимизации загрузки картинок. `decoding=async` и `loading="lazy"`

Первый можно добаавлять всем картинкам в качестве микрооптимизации. Второй имеет добавлять смысл только тем картинкам которые находятся ВНЕ первого экрана сайта (то есть ниже).

Наиболее интересный атрибут это loading="lazy"
я советую тебе [ознакомиться ](https://habr.com/ru/companies/ruvds/articles/448914/) с понятием Ленивая подгрузка изображений, это довольно интересная фишка. Долгое время ее делали на js но сейчас у нас есть обычный html-атрибут для этих целей. 

Добавлять атрибуты для оптимизации не обязательно но желательно. Это улучшит твою страницу.

2023-11-15 08:40 UTC, summertime-fms commented on hotels.html
> +      </ul>
тут все хорошо, но на этом примере хочу показать такую вещь как избыточность классов. В этом блоке мы ТОЧНО знаем что внутри li ВСЕГДА будет только ссылка. Таков этот блок. А значит и класс ссылке можно не писать -  в стилях позже можно будет просто написать селектор `.breadcrumbs-item a {}`

Таким образом сокращается количество визуального шума при взгляде на код. Ну и печатать меньше))

Такие блоки постоянно встречаются в рамках страницы - например еще соц сети в футере. 

Нынешняя реализация не считается за ошибкой, написанное выше это скорее пища на подумать. (можешь не исправлять ничего)

2023-11-15 08:40 UTC, summertime-fms commented on hotels.html
> +<div class="###">
давай придумаем класс) form-buttons например

2023-11-15 08:40 UTC, summertime-fms commented on hotels.html
> +  <!--почему у первой кнопки есть второй класс (баттон-лайт), у остальных - нет?-->
потому что у кнопки есть состояние когда она выбрана и состояние когда она не выбрана. как ты будешь стилизовать кнопку которая выбрана? для нее и нужен доп класс.

2023-11-15 08:40 UTC, summertime-fms commented on hotels.html
> +<!--в "ретро" речь идет о том, что карточки товаров обернуты в <div>. Что выбрать мне?-->
без разницы

лично мне нравятся дивы - потому что пункты списка это больше для реального списка в моем понимании. а див - нейтральный блок. еще можно юзать article - с семантической нагрузкой будет

2023-11-15 08:40 UTC, summertime-fms commented on hotels.html
> +    ВОПРОС: нужен ли мне инпут типа радио?
нет не нужен. звездочки это просто изображение как мы и обсуждали. не интерактивный элемент

2023-11-15 08:40 UTC, summertime-fms commented on hotels.html
> +	<label for="star-4" title="Оценка «4»">Рейтинг: 8,5</label>
соответственно это тоже не нужно
поменять на спан надо

2023-11-16 08:56 UTC, Roman3723 commented on hotels.html
> +      </ul>
классно, спасибо! сам сторонник анти-избыточности и вовсе не из лени)

2023-11-16 09:10 UTC, merged